spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/flydb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: sw@3100@admin
#    dynamic:
#      datasource:
#        primary:
#          url: jdbc:mysql://127.0.0.1:3306/flydb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=As
#        master:
#          url: jdbc:mysql://127.0.0.1:3306/1111111?useUnicode=true&characterEncoding=UTF-8&serverTimezone=As
